### ISSUE TITLE
curl command raising 403

### ISSUE THREAD

**Issue by ynareshkalyan21** [cowinapi/developer.cowin#116] opened 2021-05-09 10:27 UTC
curl -X GET "https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByPin?pincode=534275&date=10-05-2021" -H "accept: application/json"

output:

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: mlb-XevWMZGrt9FTHatexW7OwDAn0eQQexeFPET-FhIhoQGzJsp89w==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>%

**Comment by vaibhavsingal96** [comment] 2021-05-09 10:53
Add the following header  - 
```
'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'
```

**Comment by ynareshkalyan21** [comment] 2021-05-09 11:21
Thanks.It's  working now 👍 .

**Comment by shashi1992** [comment] 2021-05-09 11:23
Yup! Thanks for the solution!

**Comment by rishabhrkc98** [comment] 2021-05-09 11:35
Not working for me. Please Help. I am doing with PHP

   $url="https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByPin?pincode=852131&date=09-05-2021";
   $ch = curl_init();
   curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
   curl_setopt($ch, CURLOPT_VERBOSE, true);
   curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
   curl_setopt($ch, CURLOPT_HTTPHEADER, array(
        'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'       
    ));
   curl_setopt($ch, CURLOPT_URL, $url);
   $result=curl_exec($ch);
   print_r($result);


![image](https://user-images.githubusercontent.com/83907821/117570655-b45fa380-b0e8-11eb-9983-77591ce62282.png)

**Comment by rishabhrkc98** [comment] 2021-05-09 11:38
> Add the following header -
> 
> ```
> 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'
> ```

Not working for me. Please Help. I am doing with PHP

   $url="https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByPin?pincode=852131&date=09-05-2021";
   $ch = curl_init();
   curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
   curl_setopt($ch, CURLOPT_VERBOSE, true);
   curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
   curl_setopt($ch, CURLOPT_HTTPHEADER, array(
        'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'       
    ));
   curl_setopt($ch, CURLOPT_URL, $url);
   $result=curl_exec($ch);
   print_r($result);


![image](https://user-images.githubusercontent.com/83907821/117570655-b45fa380-b0e8-11eb-9983-77591ce62282.png)

**Comment by roottusk** [comment] 2021-05-09 12:26
I think the Cloudfront is having some Geolocation restriction , I have code which works on my localhost but doesn't work on the EU Server. Can any developer confirm this? @cowinapi

**Comment by rishabhrkc98** [comment] 2021-05-09 12:31
> I think the Cloudfront is having some Geolocation restriction , I have code which works on my localhost but doesn't work on the EU Server. Can any developer confirm this? @cowinapi

Yeah, I am having same problem, it is working on localhost, but not on online server. @cowinapi

**Comment by roottusk** [comment] 2021-05-09 12:36
@rishabhrkc98 Check this out https://github.com/cowinapi/developer.cowin/issues/34

**Comment by rishabhrkc98** [comment] 2021-05-09 12:41
> @rishabhrkc98 Check this out #34

Thank you @roottusk

**Comment by roottusk** [comment] 2021-05-09 12:42
Is there someway that it can still work from a non Indian IP? @cowinapi

**Comment by rohitashwachaks** [comment] 2021-05-10 05:08
Is using an Indian IP mandatory?
I have hosted my API on azure, US Central for cost benefits.
I'd really like to host it there
any idea, what to do?

**Comment by roottusk** [comment] 2021-05-10 05:12
Same for me I have hosted in Asia region but not India , would really appreciate if they could somehow whitelist our addresses or theres a way around

**Comment by Ashutosh-Karmakar** [comment] 2021-05-14 11:47
in aws after adding the user-agent also it showing 403 error but it is working nicely in my local machine
please help me with the solution

**Comment by roottusk** [comment] 2021-05-14 11:48
@Ashutosh-Karmakar Try using ap-south-1(Mumbai) region for your Server

**Comment by Ashutosh-Karmakar** [comment] 2021-05-14 19:27
Thanku , i really appriciate your help.
I was struggle with it since two days
It finally worked for me

> @Ashutosh-Karmakar Try using ap-south-1(Mumbai) region for your Server

**Comment by roottusk** [comment] 2021-05-23 15:49
Duplicate of #19

**Closed as completed** 2021-05-25 10:47 UTC
